### ISSUE TITLE
get-msidunmanagedExternaluser Unable to find type [Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser1]

### ISSUE THREAD

**Issue by bartvermeersch** [AzureAD/MSIdentityTools#18]
In PS7 I got the following errors when running Get-MsIdUnmanagedExternalUser:

InvalidOperation: C:\Users\****\PowerShell\Modules\MSIdentityTools\2.0.17\Get-MsIdUnmanagedExternalUser.ps1:64
Line |
  64 |  …             [Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser1]$u …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser1].

InvalidOperation: C:\Users\****\PowerShell\Modules\MSIdentityTools\2.0.17\Get-MsIdUnmanagedExternalUser.ps1:71
Line |
  71 |                  $mail = Get-ObjectPropertyValue $user 'mail'
     |                                                  ~~~~~
     | The variable '$user' cannot be retrieved because it has not been set.

After explicitly importing the Users graph module, the type was recognized: 

import-Module Microsoft.Graph.Users

**Comment by merill** [comment]
Created a PR to fix this #19

**Comment by merill** [comment]
Fixed in latest module.
