### ISSUE TITLE
Missing information in results from Resolve-MsIdTenant using WPS 5.x

### ISSUE THREAD

**Issue by JefTek** [AzureAD/MSIdentityTools#2]
When running Resolve-MsIdTenant in Windows PowerShell 5.x, not all tenant details are returned and appears as null values.

It is recommended to use at least PowerShell 7.2 for running cmdlets in the MSIdentityTools module as there is limited support for testing in WPS 5.1 and will be best effort for supporting the earlier WPS versions.

**Comment by bsj17** [comment]
Hi, what kind of permissions do you need to read tenant displayName and defaultdomain  name?
Environment                   : Global
ValueToResolve                : microsoft.com
ValueFormat                   : DomainName
Result                        : Error
ResultMessage                 : **Response status code does not indicate success: Forbidden (Forbidden).**
TenantId                      :
DisplayName                   :
DefaultDomainName             :
FederationBrandName           :
OidcMetadataResult            : Resolved
OidcMetadataTenantId          : 72f988bf-86f1-41af-91ab-2d7cd011db47
OidcMetadataTenantRegionScope : WW


Environment                   : Global
ValueToResolve                : 72f988bf-86f1-41af-91ab-2d7cd011db47
ValueFormat                   : TenantId
Result                        : Error
ResultMessage                 : **Response status code does not indicate success: Forbidden (Forbidden).**
TenantId                      :
DisplayName                   :
DefaultDomainName             :
FederationBrandName           :
OidcMetadataResult            : Resolved
OidcMetadataTenantId          : 72f988bf-86f1-41af-91ab-2d7cd011db47
OidcMetadataTenantRegionScope : WW

**Comment by JefTek** [comment]
@bsj17 You need the CrossTenantInformation.ReadBasic.All permission scope.   While it was in the PS help,  I am going to add a warning to the cmdlet if it is not currently in the scopes for the connection.
