### ISSUE TITLE
Get-MsIdUnmanagedExternalUser, Does not check of Permission

### ISSUE THREAD

**Issue by weyCC81** [AzureAD/MSIdentityTools#20]
**Describe the bug**
For the Command "Get-MsIdUnmanagedExternalUser" i get the following Error "403 Forbidden - Insufficient privileges to complete the operation".

**To Reproduce**
1. Command 'Connect-MgGraph' (without any Permission, not sure waht is needed from wiki)
2. Command 'Get-MsIdUnmanagedExternalUser'

**Expected behavior**
I would expect an error like in "Get-MsIdApplicationIdByAppId":
Test-MgCommand : Additional scope needed for command 'X', call Connect-MgGraph with one of the following scopes: Application.Read.All,
Application.ReadWrite.All, Directory.Read.All

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - PowerShell Version: 5.1.22000.832
 - MS Graph SDK PowerShell Module Version: 1.7.0

**Additional context**
https://github.com/AzureAD/MSIdentityTools/wiki/Cmdlets --> Table is not shown fully

**Comment by jasoth** [comment]
@weyCC81 I have updated all commands that use Mg modules to use the Test-MgCommand function so you should get more consistent errors now. Additionally, I added some logic to avoid situations where User.Read passes the check even when User.Read.All is really required. Please reopen this issue, if you are still not seeing a scope suggestion to resolve the insufficient privileges error.
