### ISSUE TITLE
Update wiki (deprication, addition)

### ISSUE THREAD

**Issue by weyCC81** [AzureAD/MSIdentityTools#22]
MSIdentityTools.wiki\Cmdlets.md
| [Get-MsIdInactiveSignInUser](./Get-MsIdInactiveSignInUser) | (Deprecated) Retrieve Users who have not had interactive sign ins since XX days ago |
| [Get-MsIdIsViralUser](./Get-MsIdIsViralUser) | Returns true if the user's mail domain is a viral (unmanaged) Azure AD tenant. To learn more about viral tenants see Take over an unmanaged directory as administrator in Azure Active Directory](https://docs.microsoft.com/azure/active-directory/enterprise-users/domains-admin-takeover) |

| [Get-MsIdUnredeemedInvitedUser](./Get-MsIdUnredeemedInvitedUser) | Retrieve Users who have not had interactive sign ins since XX days ago |

| [ConvertFrom-MsIdAzureAdImmutableId](./ConvertFrom-MsIdAzureAdImmutableId) | (New) |
| [ConvertFrom-MsIdSamlRequest](./ConvertFrom-MsIdSamlRequest) | (New) |
| [ConvertFrom-MsIdSamlResponse](./ConvertFrom-MsIdSamlResponse) |(New) |
| [Get-MsIdWsFedFederationMetadata](./Get-MsIdWsFedFederationMetadata) | (New) |

MSIdentityTools.wiki\Get-MsIdInactiveSignInUser.md
# Get-MsIdInactiveSignInUser (Deprecated)

MSIdentityTools.wiki\Get-MsIdUnmanagedExternalUsers.md
# Get-MsIdUnmanagedExternalUsers (Deprecated)

MSIdentityTools.wiki\Get-MsIdUnredeemedInvitedUser.md
# Get-MsIdUnredeemedInvitedUser (Deprecated)

MSIdentityTools.wiki\ConvertFrom-MsIdAzureAdImmutableId.md
# ConvertFrom-MsIdAzureAdImmutableId (New)

MSIdentityTools.wiki\ConvertFrom-MsIdSamlRequest.md
# ConvertFrom-MsIdSamlRequest (New)

MSIdentityTools.wiki\ConvertFrom-MsIdSamlResponse.md
# ConvertFrom-MsIdSamlResponse (New)

MSIdentityTools.wiki\Get-MsIdWsFedFederationMetadata.md
# Get-MsIdWsFedFederationMetadata (New)

**Comment by merill** [comment]
Thanks for reporting. This has been fixed. The docs are now at https://aka.ms/msid
