### ISSUE TITLE
Wiki table broken

### ISSUE THREAD

**Issue by jannickoeben** [AzureAD/MSIdentityTools#27]
### Describe the bug

Wiki page table is broken
https://github.com/AzureAD/MSIdentityTools/wiki/Cmdlets

### To Reproduce

Check the page https://github.com/AzureAD/MSIdentityTools/wiki/Cmdlets. The table is broken.

### Expected behavior

A nice formatted table.

### Screenshots

https://github.com/AzureAD/MSIdentityTools/wiki/Cmdlets

### Environment (please complete the following information)

all browsers

### Additional context

not applicable

**Comment by merill** [comment]
Thanks for the call out. This has been fixed.
