### ISSUE TITLE
Export-MsIdAppConsentGrantReport

### ISSUE THREAD

**Issue by ddonders** [AzureAD/MSIdentityTools#44]
### Describe the bug

When running Export-MsIdAppConsentGrantReport there is the following error returned: PropertyNotFoundException: The property 'AdditionalProperties' cannot be found on this object. Verify that the property exists.

### To Reproduce

Just ran the command.

### Expected behavior

No errors.

### Screenshots

![image](https://github.com/AzureAD/MSIdentityTools/assets/22054719/536607e9-0ae2-450a-b162-e20753b92cb0)

### Environment (please complete the following information)

- Operating System: Windows 11
- PowerShell Version: PowerShell 7.2

### Additional context

NA

**Comment by jasperbaes** [comment]
@merill 

Same issue here. When running the command with the '-Verbose' parameter, numerous errors flood the output:

```
Get-MgDirectoryObjectById_GetExpanded: Method not found: 'System.Net.Http.HttpClient
Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient(System.Management.Automation.InvocationInfo,
Microsoft.Graph.PowerShell.Authentication.IAuthContext)'.
PropertyNotFoundException: The property 'AdditionalProperties' cannot be found on this object. Verify that the property exists.
```

With PowerShell 7.4.1 on Windows 11

**Comment by jasperbaes** [comment]
I successfully tested this again on an Azure VM using PowerShell 7.4.1 without encountering any errors. Ensure that you first run "Install-Module Microsoft.Graph". However, I'm still experiencing issues on my host machine.

Additionally, the pivot tables in the Excel file loaded correctly only after uploading to SharePoint, not when opening from a local folder.

**Comment by merill** [comment]
Thanks for testing and confirming it works.
