### ISSUE TITLE
Example 1 Typo in Export-MsIdAppConsentGrantReport wiki

### ISSUE THREAD

**Issue by brianreidc7** [AzureAD/MSIdentityTools#45]
### Describe the bug

Typo in the documentation page for https://github.com/AzureAD/MSIdentityTools/wiki/Export-MsIdAppConsentGrantReport - under Example 1

### Expected behavior

Connect-MgGra*p*h -Scopes Directory.Read.All

### Current Text

"g" not "p"
Connect-MgGra*g*h -Scopes Directory.Read.All

**Comment by merill** [comment]
Thanks for reporting this @brianreidc7 

It's been fixed now. See https://azuread.github.io/MSIdentityTools/commands/Export-MsIdAppConsentGrantReport
