### ISSUE TITLE
Get-MsIdInactiveSignInUser fails to "Find-MgGraphCommand: 'Get-MgUser'"

### ISSUE THREAD

**Issue by matthewjlevy** [AzureAD/MSIdentityTools#47]
### Describe the bug
When Running the command "Get-MsIdInactiveSignInUser -LastSignInBeforeDaysAgo 60 -UserType Guest the function can't find the Get-MgUser command.

### To Reproduce
I have installed the latest version (2.0.52) of MsIdentityTools and Microsoft.Graph.Users version 2.12.0
get-command get-MgUser

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-MgUser                                         2.12.0     Microsoft.Graph.Users

Steps to reproduce:
Run connect-MgGraph -Scopes "Application.Read.all","Directory.Read.All","User.Read.All"copes.
Run Get-MsIdInactiveSignInUser -LastSignInBeforeDaysAgo 60 -UserType Guest

### Expected behavior

Output of Inactive Guest Users

### Screenshots
![image](https://github.com/AzureAD/MSIdentityTools/assets/27995471/bd2f9348-4089-47ef-8ace-d9182f39582c)

### Environment (please complete the following information)

- Operating System: Windows 11
- PowerShell Version: PowerShell 7.3.11 ]
- MS Graph PowerShell SDK Module Version: 2.12.0

**Comment by BohrenAn** [comment]
Same here, i tracked down the issue and created a Pull Request https://github.com/AzureAD/MSIdentityTools/pull/40

**Comment by BohrenAn** [comment]
By the way the way, the Error: "is not a valid Microsoft Graph PowerShell command" happens at multiple commands
- Get-MsIdGroupWithExpiration
- Get-MsIdInactiveSignInUser -LastSignInBeforeDaysAgo 30
![image](https://github.com/AzureAD/MSIdentityTools/assets/45082822/88a16780-2132-4d06-a199-751feb541078)

@merill 
Can you please review the Pull Request?

Regards
Andres

**Comment by BohrenAn** [comment]
Also Bugreport has been created in MSGraph-SDK-PowerShell to solve the root issue
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2582

**Comment by BohrenAn** [comment]
This Issue has been fixed with Version 2.0.57. Issue can be closed now

**Comment by matthewjlevy** [comment]
Thank you Andres, I will check it out
________________________________
