### ISSUE TITLE
Syntax error: character '%' is not valid at position 172

### ISSUE THREAD

**Issue by rafaj-ps** [AzureAD/MSIdentityTools#54]
### Describe the bug

When I run "Export-MsIdAzureMfaReport .\report.xlsx" I get following error: 

Write-Error: Invalid filter clause: Syntax error: character '%' is not valid at position 172 in '(appid eq
'c44b4083-3bb0-49c1-b47d-974e53cbdf3c' or appid eq '04b07795-8ddb-461a-bbee-02f9e1bf7b46' or appid eq
'1950a258-227b-4e31-a9cf-717495945fc2') and status/errorcode%20eq%200%20&$top=1&$orderby=createdDateTime%20asc'.

### To Reproduce

run "Export-MsIdAzureMfaReport .\report.xlsx" 

### Expected behavior

A report should be generated

### Environment (please complete the following information)
Windows 11
PS Version:
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      3

**Comment by tinojr** [comment]
I have this same issue.

**Comment by tinojr** [comment]
@merill Are you aware of this issue? Running the following produces the error above. I looked in the code, and it seems to be generated by a helper function. Can you please look into this?

Install-Module MsIdentityTools -Scope CurrentUser
Connect-MgGraph -Scopes Directory.Read.All, AuditLog.Read.All, UserAuthenticationMethod.Read.All
Export-MsIdAzureMfaReport .\report.xlsx

**Comment by merill** [comment]
Can you update Graph PowerShell to the latest version?

```
Update-Module Microsoft.Graph
```

I believe this was a bug in a previous version.

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2715

**Comment by tinojr** [comment]
Thanks @merill ! I was on version 2.18.0 and I just updated to 2.20.0 and it's working. Please, please, please call this out in the kb that version 2.20.0 is required. Thank you!

**Comment by rafaj-ps** [comment]
Thanks @merill. Module update also works for me.
