### ISSUE TITLE
Command "Update-InvitedUserSponsorsFromInvitedBy" in docs not in module

### ISSUE THREAD

**Issue by TomAafloen** [AzureAD/MSIdentityTools#56]
Hi!
The documentation mentions a command called **Update-InvitedUserSponsorsFromInvitedBy**:
https://azuread.github.io/MSIdentityTools/commands/Update-InvitedUserSponsorsFromInvitedBy

But the MSIdentityTools module does not have that command:
![Image](https://github.com/AzureAD/MSIdentityTools/assets/29425904/ec9fd102-fc4e-4cf5-b9e2-c7f172c0a5c9)

Looking forward to that command, but maybe documentation should be synced with availabe commands, or at least have a _planned_ flag or similar?

Thanks for the great work!

**Comment by merill** [comment]
Fixed. Please update to the latest version.
