### ISSUE TITLE
Export-MsIdAzureMfaReport

### ISSUE THREAD

**Issue by emcera** [AzureAD/MSIdentityTools#67]
As described, the **Export-MsIdAzureMfaReport** "exports the list of users that have signed into the Azure portal, Azure CLI, or Azure PowerShell over the last 30 days by querying the sign-in logs. In [Microsoft Entra ID Free](https://learn.microsoft.com/entra/identity/monitoring-health/reference-reports-data-retention#activity-reports) tenants, sign-in log retention is limited to seven days."

Since Microsoft will soon require MFA for the Entra admin center, Intune admin center, such as Windows 365 Cloud PC, could you please update the report to include activities from these services as well?

Thank you!

**Comment by merill** [comment]
Due to the way App IDs etc work the list of users you see includes portals that depend on the Azure Portal. 

So when you see Azure Portal ticked it includes Entra, Intune etc as well.
