### ISSUE TITLE
Get-MsIdCrossTenantAccessActivity returns invalid filter clause

### ISSUE THREAD

**Issue by AndyStephens** [AzureAD/MSIdentityTools#9]
Connect-MgGraph -Scopes AuditLog.Read.All
Get-MsIdCrossTenantAccessActivity -AccessDirection Inbound

Returns:
Line |
 271 |  …             $SignIns = Get-MgAuditLogSignIn -Filter ("HomeTenantId ne …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid filter clause

WARNING: 18:51:31 - No sign-ins matching the selected criteria found.

 - OS: WIN10
 - PowerShell Version: PowerShell 7.2 
 - MS Graph SDK PowerShell Module Version: 1.9.3

![image](https://user-images.githubusercontent.com/101744683/158665852-8f0fac4c-2e23-4530-b1d1-3841f367f9dd.png)
![image](https://user-images.githubusercontent.com/101744683/158666551-1d36fef2-5d69-43e4-9841-18a9f726970f.png)

**Comment by netracksolutions** [comment]
@JefTek  @f4rty  The debug switch returns the same output

It seems to be this filter that is failing:

`$SignIns = Get-MgAuditLogSignIn -Filter ("HomeTenantId ne '{0}' and TokenIssuerType eq 'AzureAD'" -f (Get-MgContext).TenantId) -All:$True | Group-Object HomeTenantID`
                


Running:

`PS C:\Users\username> $signins = Get-MgAuditLogSignIn
PS C:\Users\username> $SignIns[1] | fl`

Only returns these attributes:

AppDisplayName
AppId
AppliedConditionalAccessPolicies
ClientAppUsed
ConditionalAccessStatus
CorrelationId
CreatedDateTime
DeviceDetail
IPAddress
Id
IsInteractive
Location
ResourceDisplayName
ResourceId
RiskDetail
RiskEventTypes
RiskEventTypesV2
RiskLevelAggregated
RiskLevelDuringSignIn
RiskState
Status
UserDisplayName
UserId
UserPrincipalName
AdditionalProperties


So looks like the filter is looking for values that do not exist?

**Comment by f4rty** [comment]
@AndyStephens , @netracksolutions - thank you.

Can you check if you're calling the beta API, please? 
`Get-MgProfile`
`Select-MgProfile -Name beta`

The function is supposed to pick up if you aren't.

**Comment by AndyStephens** [comment]
@f4rty Yes Beta is being used (and it prompts to use)

![image](https://user-images.githubusercontent.com/101744683/160838961-d3ee2c17-0cc1-4be5-afff-a2887d1ecf99.png)

**Comment by f4rty** [comment]
@AndyStephens - thx, again.

What happens when you run the following?

`Get-MgAuditLogSignIn -Filter ("HomeTenantId ne '{0}' and TokenIssuerType eq 'AzureAD'" -f (Get-MgContext).TenantId) -Debug`

**Comment by AndyStephens** [comment]
@f4rty  here you go

![image](https://user-images.githubusercontent.com/101744683/161075841-997e16a8-51ce-4c4e-9556-6f7921b9f263.png)

**Comment by davis-x** [comment]
FYI I'm seeing the exact same behaviour 
```
 PS C:\Users\User> Get-MsIdCrossTenantAccessActivity
Get-MgAuditLogSignIn_List: C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.13\Get-MsIdCrossTenantAccessActivity.ps1:298
Line |
 298 |  …             $Outbound = Get-MgAuditLogSignIn -Filter ("ResourceTenant …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid filter clause

Get-MgAuditLogSignIn_List: C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.13\Get-MsIdCrossTenantAccessActivity.ps1:303
Line |
 303 |  …             $Inbound = Get-MgAuditLogSignIn -Filter ("HomeTenantId ne …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid filter clause

WARNING: 4:20:05 PM - No sign-ins matching the selected criteria found.
PS C:\Users\User>
````

**Comment by bartvermeersch** [comment]
Adding Directory.Read.All permission doesn't help.

**Comment by bartvermeersch** [comment]
Updating to the latest version of the SDK solved the issue (together with choosing the beta graph and the permissions AuditLog.Read.All, Directory.Read.All, CrossTenantInformation.ReadBasic.All)

**Comment by JelleDemets** [comment]
> Updating to the latest version of the SDK solved the issue (together with choosing the beta graph and the permissions AuditLog.Read.All, Directory.Read.All, CrossTenantInformation.ReadBasic.All)

Did you have to  update to PS 7.2 for it to solve the problem?

**Comment by UserNameIsUnavailable2** [comment]
> Updating to the latest version of the SDK solved the issue (together with choosing the beta graph and the permissions AuditLog.Read.All, Directory.Read.All, CrossTenantInformation.ReadBasic.All)

Did you have to update to PS 7.2 for it to work?

**Comment by JefTek** [comment]
So looking at the above and in my lab, even though  I am specifying the beta profile for the beta endpoint, the Get-mgAuditSIgnIn is actually calling the v1.0 endpoint and throwing the filter error using the 1.10.0 version.
![image](https://user-images.githubusercontent.com/11558645/181393926-4f9951a8-42fd-4e5c-ac83-00ad9f66cd72.png)
I'll open an issue for that cmdlet on the main MS Graph SDK PowerShell repo since that is unexpected I believe.
